// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  EventsReadEventsData,
  EventsReadEventsResponse,
  EventsCreateNewEventData,
  EventsCreateNewEventResponse,
  EventsUpdateExistingEventData,
  EventsUpdateExistingEventResponse,
  EventsDeleteExistingEventData,
  EventsDeleteExistingEventResponse,
  EventsReadEventDetailsData,
  EventsReadEventDetailsResponse,
  EventsCreateEventDetailsRouteData,
  EventsCreateEventDetailsRouteResponse,
  EventsUpdateEventDetailsRouteData,
  EventsUpdateEventDetailsRouteResponse,
  EventsReadEventRegistrationData,
  EventsReadEventRegistrationResponse,
  EventsUpdateEventRegistrationRouteData,
  EventsUpdateEventRegistrationRouteResponse,
  EventsDeleteEventRegistrationRouteData,
  EventsDeleteEventRegistrationRouteResponse,
  EventsCreateEventRegistrationRouteData,
  EventsCreateEventRegistrationRouteResponse,
  EventsReadEventBySlugData,
  EventsReadEventBySlugResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  OrganizationsListOrganizationsRouteData,
  OrganizationsListOrganizationsRouteResponse,
  OrganizationsCreateOrganizationRouteData,
  OrganizationsCreateOrganizationRouteResponse,
  OrganizationsGetOrganizationRouteData,
  OrganizationsGetOrganizationRouteResponse,
  OrganizationsUpdateOrganizationRouteData,
  OrganizationsUpdateOrganizationRouteResponse,
  OrganizationsDeleteOrganizationRouteData,
  OrganizationsDeleteOrganizationRouteResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  SessionsReadSessionsData,
  SessionsReadSessionsResponse,
  SessionsReadSessionData,
  SessionsReadSessionResponse,
  SessionsUpdateSessionRouteData,
  SessionsUpdateSessionRouteResponse,
  SessionsDeleteSessionRouteData,
  SessionsDeleteSessionRouteResponse,
  SessionsSubmitSessionRouteData,
  SessionsSubmitSessionRouteResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
} from "./types.gen"

export class EventsService {
  /**
   * Read Events
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.skip
   * @param data.limit
   * @returns Event Successful Response
   * @throws ApiError
   */
  public static readEvents(
    data: EventsReadEventsData,
  ): CancelablePromise<EventsReadEventsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/orgs/{organization_slug}/e/",
      path: {
        organization_slug: data.organizationSlug,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create New Event
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.requestBody
   * @returns Event Successful Response
   * @throws ApiError
   */
  public static createNewEvent(
    data: EventsCreateNewEventData,
  ): CancelablePromise<EventsCreateNewEventResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/orgs/{organization_slug}/e/",
      path: {
        organization_slug: data.organizationSlug,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Existing Event
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.requestBody
   * @returns Event Successful Response
   * @throws ApiError
   */
  public static updateExistingEvent(
    data: EventsUpdateExistingEventData,
  ): CancelablePromise<EventsUpdateExistingEventResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Existing Event
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteExistingEvent(
    data: EventsDeleteExistingEventData,
  ): CancelablePromise<EventsDeleteExistingEventResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Event Details
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @returns EventDetails Successful Response
   * @throws ApiError
   */
  public static readEventDetails(
    data: EventsReadEventDetailsData,
  ): CancelablePromise<EventsReadEventDetailsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/details",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Event Details Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.requestBody
   * @returns EventDetails Successful Response
   * @throws ApiError
   */
  public static createEventDetailsRoute(
    data: EventsCreateEventDetailsRouteData,
  ): CancelablePromise<EventsCreateEventDetailsRouteResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/details",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Event Details Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.requestBody
   * @returns EventDetails Successful Response
   * @throws ApiError
   */
  public static updateEventDetailsRoute(
    data: EventsUpdateEventDetailsRouteData,
  ): CancelablePromise<EventsUpdateEventDetailsRouteResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/details",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Event Registration
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.registrationId
   * @returns EventRegistration Successful Response
   * @throws ApiError
   */
  public static readEventRegistration(
    data: EventsReadEventRegistrationData,
  ): CancelablePromise<EventsReadEventRegistrationResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/registrations/{registration_id}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
        registration_id: data.registrationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Event Registration Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.registrationId
   * @param data.requestBody
   * @returns EventRegistration Successful Response
   * @throws ApiError
   */
  public static updateEventRegistrationRoute(
    data: EventsUpdateEventRegistrationRouteData,
  ): CancelablePromise<EventsUpdateEventRegistrationRouteResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/registrations/{registration_id}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
        registration_id: data.registrationId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Event Registration Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.registrationId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteEventRegistrationRoute(
    data: EventsDeleteEventRegistrationRouteData,
  ): CancelablePromise<EventsDeleteEventRegistrationRouteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/registrations/{registration_id}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
        registration_id: data.registrationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Event Registration Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.requestBody
   * @returns EventRegistration Successful Response
   * @throws ApiError
   */
  public static createEventRegistrationRoute(
    data: EventsCreateEventRegistrationRouteData,
  ): CancelablePromise<EventsCreateEventRegistrationRouteResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/registrations/",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Event By Slug
   * Fetch an event by its slug.
   * @param data The data for the request.
   * @param data.eventSlug
   * @returns Event Successful Response
   * @throws ApiError
   */
  public static readEventBySlug(
    data: EventsReadEventBySlugData,
  ): CancelablePromise<EventsReadEventBySlugResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/events/{event_slug}",
      path: {
        event_slug: data.eventSlug,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class OrganizationsService {
  /**
   * List Organizations Route
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns OrganizationList Successful Response
   * @throws ApiError
   */
  public static listOrganizationsRoute(
    data: OrganizationsListOrganizationsRouteData = {},
  ): CancelablePromise<OrganizationsListOrganizationsRouteResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/orgs/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Organization Route
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Organization Successful Response
   * @throws ApiError
   */
  public static createOrganizationRoute(
    data: OrganizationsCreateOrganizationRouteData,
  ): CancelablePromise<OrganizationsCreateOrganizationRouteResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/orgs/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Organization Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @returns Organization Successful Response
   * @throws ApiError
   */
  public static getOrganizationRoute(
    data: OrganizationsGetOrganizationRouteData,
  ): CancelablePromise<OrganizationsGetOrganizationRouteResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/orgs/{organization_slug}",
      path: {
        organization_slug: data.organizationSlug,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Organization Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.requestBody
   * @returns Organization Successful Response
   * @throws ApiError
   */
  public static updateOrganizationRoute(
    data: OrganizationsUpdateOrganizationRouteData,
  ): CancelablePromise<OrganizationsUpdateOrganizationRouteResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/orgs/{organization_slug}",
      path: {
        organization_slug: data.organizationSlug,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Organization Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteOrganizationRoute(
    data: OrganizationsDeleteOrganizationRouteData,
  ): CancelablePromise<OrganizationsDeleteOrganizationRouteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/orgs/{organization_slug}",
      path: {
        organization_slug: data.organizationSlug,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class SessionsService {
  /**
   * Read Sessions
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.skip
   * @param data.limit
   * @returns Session Successful Response
   * @throws ApiError
   */
  public static readSessions(
    data: SessionsReadSessionsData,
  ): CancelablePromise<SessionsReadSessionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Session
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.sessionSlug
   * @returns Session Successful Response
   * @throws ApiError
   */
  public static readSession(
    data: SessionsReadSessionData,
  ): CancelablePromise<SessionsReadSessionResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/s/{session_slug}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
        session_slug: data.sessionSlug,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Session Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.sessionSlug
   * @param data.requestBody
   * @returns Session Successful Response
   * @throws ApiError
   */
  public static updateSessionRoute(
    data: SessionsUpdateSessionRouteData,
  ): CancelablePromise<SessionsUpdateSessionRouteResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/s/{session_slug}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
        session_slug: data.sessionSlug,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Session Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.sessionSlug
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteSessionRoute(
    data: SessionsDeleteSessionRouteData,
  ): CancelablePromise<SessionsDeleteSessionRouteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/s/{session_slug}",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
        session_slug: data.sessionSlug,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Submit Session Route
   * @param data The data for the request.
   * @param data.organizationSlug
   * @param data.eventSlug
   * @param data.requestBody
   * @returns Session Successful Response
   * @throws ApiError
   */
  public static submitSessionRoute(
    data: SessionsSubmitSessionRouteData,
  ): CancelablePromise<SessionsSubmitSessionRouteResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/orgs/{organization_slug}/e/{event_slug}/submit",
      path: {
        organization_slug: data.organizationSlug,
        event_slug: data.eventSlug,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}
