"""update

Revision ID: b08d69908e8d
Revises: 1a31ce608336
Create Date: 2025-05-12 11:17:56.485967

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b08d69908e8d'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('friendly_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('apt_suite', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('linkedin_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('readme', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('event',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('VIRTUAL', 'IN_PERSON', 'HYBRID', name='eventtype'), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organizationadminlink',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('organizationmemberlink',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('current_position', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('current_company', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('github', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('twitter', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('work_experience', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('education', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('projects', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('certifications', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_userprofile_username'), 'userprofile', ['username'], unique=True)
    op.create_table('eventdetails',
    sa.Column('readme', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code_of_conduct', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sponsors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('info_for_speakers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('info_for_sponsors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('info_for_staff', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resources', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('eventorganizerlink',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('eventregistration',
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'CANCELED', name='eventregistrationstatus'), nullable=False),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_speaker', sa.Boolean(), nullable=False),
    sa.Column('is_organizer', sa.Boolean(), nullable=False),
    sa.Column('is_sponsor', sa.Boolean(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('level', sa.Enum('LEVEL_100', 'LEVEL_200', 'LEVEL_300', 'LEVEL_400', name='sessionlevel'), nullable=False),
    sa.Column('session_type', sa.Enum('VIRTUAL', 'IN_PERSON', 'HYBRID', name='sessiontype'), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sessionregistration',
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'CANCELED', name='sessionregistrationstatus'), nullable=False),
    sa.Column('cancelation_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionspeakerlink',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'user_id')
    )
    op.create_table('sessionreview',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_registration_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_registration_id'], ['sessionregistration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionreview')
    op.drop_table('sessionspeakerlink')
    op.drop_table('sessionregistration')
    op.drop_table('session')
    op.drop_table('eventregistration')
    op.drop_table('eventorganizerlink')
    op.drop_table('eventdetails')
    op.drop_index(op.f('ix_userprofile_username'), table_name='userprofile')
    op.drop_table('userprofile')
    op.drop_table('organizationmemberlink')
    op.drop_table('organizationadminlink')
    op.drop_table('event')
    op.drop_table('organization')
    op.drop_table('address')
    # ### end Alembic commands ###
