/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthSettingsImport } from './routes/_auth/settings'
import { Route as AuthAdminImport } from './routes/_auth/admin'
import { Route as AuthOrglayoutImport } from './routes/_auth/_org_layout'
import { Route as AuthEventlayoutImport } from './routes/_auth/_event_layout'
import { Route as AuthBaseImport } from './routes/_auth/_base'
import { Route as AuthOrglayoutOrgsIndexImport } from './routes/_auth/_org_layout/orgs.index'
import { Route as AuthEventlayoutOrgslugEventslugIndexImport } from './routes/_auth/_event_layout/$org_slug.$event_slug.index'
import { Route as AuthOrglayoutOrgsOrgslugEventsImport } from './routes/_auth/_org_layout/orgs.$org_slug.events'
import { Route as AuthEventlayoutOrgslugEventslugSponsorsImport } from './routes/_auth/_event_layout/$org_slug.$event_slug.sponsors'
import { Route as AuthEventlayoutOrgslugEventslugSpeakersImport } from './routes/_auth/_event_layout/$org_slug.$event_slug.speakers'
import { Route as AuthEventlayoutOrgslugEventslugSettingsImport } from './routes/_auth/_event_layout/$org_slug.$event_slug.settings'
import { Route as AuthEventlayoutOrgslugEventslugAttendeesImport } from './routes/_auth/_event_layout/$org_slug.$event_slug.attendees'
import { Route as AuthEventlayoutOrgslugEventslugSessionsIndexImport } from './routes/_auth/_event_layout/$org_slug.$event_slug.sessions.index'
import { Route as AuthEventlayoutOrgslugEventslugSessionsSessionslugImport } from './routes/_auth/_event_layout/$org_slug.$event_slug.sessions.$session_slug'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSettingsRoute = AuthSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminRoute = AuthAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthOrglayoutRoute = AuthOrglayoutImport.update({
  id: '/_org_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthEventlayoutRoute = AuthEventlayoutImport.update({
  id: '/_event_layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthBaseRoute = AuthBaseImport.update({
  id: '/_base',
  getParentRoute: () => AuthRoute,
} as any)

const AuthOrglayoutOrgsIndexRoute = AuthOrglayoutOrgsIndexImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthOrglayoutRoute,
} as any)

const AuthEventlayoutOrgslugEventslugIndexRoute =
  AuthEventlayoutOrgslugEventslugIndexImport.update({
    id: '/$org_slug/$event_slug/',
    path: '/$org_slug/$event_slug/',
    getParentRoute: () => AuthEventlayoutRoute,
  } as any)

const AuthOrglayoutOrgsOrgslugEventsRoute =
  AuthOrglayoutOrgsOrgslugEventsImport.update({
    id: '/orgs/$org_slug/events',
    path: '/orgs/$org_slug/events',
    getParentRoute: () => AuthOrglayoutRoute,
  } as any)

const AuthEventlayoutOrgslugEventslugSponsorsRoute =
  AuthEventlayoutOrgslugEventslugSponsorsImport.update({
    id: '/$org_slug/$event_slug/sponsors',
    path: '/$org_slug/$event_slug/sponsors',
    getParentRoute: () => AuthEventlayoutRoute,
  } as any)

const AuthEventlayoutOrgslugEventslugSpeakersRoute =
  AuthEventlayoutOrgslugEventslugSpeakersImport.update({
    id: '/$org_slug/$event_slug/speakers',
    path: '/$org_slug/$event_slug/speakers',
    getParentRoute: () => AuthEventlayoutRoute,
  } as any)

const AuthEventlayoutOrgslugEventslugSettingsRoute =
  AuthEventlayoutOrgslugEventslugSettingsImport.update({
    id: '/$org_slug/$event_slug/settings',
    path: '/$org_slug/$event_slug/settings',
    getParentRoute: () => AuthEventlayoutRoute,
  } as any)

const AuthEventlayoutOrgslugEventslugAttendeesRoute =
  AuthEventlayoutOrgslugEventslugAttendeesImport.update({
    id: '/$org_slug/$event_slug/attendees',
    path: '/$org_slug/$event_slug/attendees',
    getParentRoute: () => AuthEventlayoutRoute,
  } as any)

const AuthEventlayoutOrgslugEventslugSessionsIndexRoute =
  AuthEventlayoutOrgslugEventslugSessionsIndexImport.update({
    id: '/$org_slug/$event_slug/sessions/',
    path: '/$org_slug/$event_slug/sessions/',
    getParentRoute: () => AuthEventlayoutRoute,
  } as any)

const AuthEventlayoutOrgslugEventslugSessionsSessionslugRoute =
  AuthEventlayoutOrgslugEventslugSessionsSessionslugImport.update({
    id: '/$org_slug/$event_slug/sessions/$session_slug',
    path: '/$org_slug/$event_slug/sessions/$session_slug',
    getParentRoute: () => AuthEventlayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_base': {
      id: '/_auth/_base'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthBaseImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_event_layout': {
      id: '/_auth/_event_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthEventlayoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_org_layout': {
      id: '/_auth/_org_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthOrglayoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminImport
      parentRoute: typeof AuthImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_org_layout/orgs/': {
      id: '/_auth/_org_layout/orgs/'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthOrglayoutOrgsIndexImport
      parentRoute: typeof AuthOrglayoutImport
    }
    '/_auth/_event_layout/$org_slug/$event_slug/attendees': {
      id: '/_auth/_event_layout/$org_slug/$event_slug/attendees'
      path: '/$org_slug/$event_slug/attendees'
      fullPath: '/$org_slug/$event_slug/attendees'
      preLoaderRoute: typeof AuthEventlayoutOrgslugEventslugAttendeesImport
      parentRoute: typeof AuthEventlayoutImport
    }
    '/_auth/_event_layout/$org_slug/$event_slug/settings': {
      id: '/_auth/_event_layout/$org_slug/$event_slug/settings'
      path: '/$org_slug/$event_slug/settings'
      fullPath: '/$org_slug/$event_slug/settings'
      preLoaderRoute: typeof AuthEventlayoutOrgslugEventslugSettingsImport
      parentRoute: typeof AuthEventlayoutImport
    }
    '/_auth/_event_layout/$org_slug/$event_slug/speakers': {
      id: '/_auth/_event_layout/$org_slug/$event_slug/speakers'
      path: '/$org_slug/$event_slug/speakers'
      fullPath: '/$org_slug/$event_slug/speakers'
      preLoaderRoute: typeof AuthEventlayoutOrgslugEventslugSpeakersImport
      parentRoute: typeof AuthEventlayoutImport
    }
    '/_auth/_event_layout/$org_slug/$event_slug/sponsors': {
      id: '/_auth/_event_layout/$org_slug/$event_slug/sponsors'
      path: '/$org_slug/$event_slug/sponsors'
      fullPath: '/$org_slug/$event_slug/sponsors'
      preLoaderRoute: typeof AuthEventlayoutOrgslugEventslugSponsorsImport
      parentRoute: typeof AuthEventlayoutImport
    }
    '/_auth/_org_layout/orgs/$org_slug/events': {
      id: '/_auth/_org_layout/orgs/$org_slug/events'
      path: '/orgs/$org_slug/events'
      fullPath: '/orgs/$org_slug/events'
      preLoaderRoute: typeof AuthOrglayoutOrgsOrgslugEventsImport
      parentRoute: typeof AuthOrglayoutImport
    }
    '/_auth/_event_layout/$org_slug/$event_slug/': {
      id: '/_auth/_event_layout/$org_slug/$event_slug/'
      path: '/$org_slug/$event_slug'
      fullPath: '/$org_slug/$event_slug'
      preLoaderRoute: typeof AuthEventlayoutOrgslugEventslugIndexImport
      parentRoute: typeof AuthEventlayoutImport
    }
    '/_auth/_event_layout/$org_slug/$event_slug/sessions/$session_slug': {
      id: '/_auth/_event_layout/$org_slug/$event_slug/sessions/$session_slug'
      path: '/$org_slug/$event_slug/sessions/$session_slug'
      fullPath: '/$org_slug/$event_slug/sessions/$session_slug'
      preLoaderRoute: typeof AuthEventlayoutOrgslugEventslugSessionsSessionslugImport
      parentRoute: typeof AuthEventlayoutImport
    }
    '/_auth/_event_layout/$org_slug/$event_slug/sessions/': {
      id: '/_auth/_event_layout/$org_slug/$event_slug/sessions/'
      path: '/$org_slug/$event_slug/sessions'
      fullPath: '/$org_slug/$event_slug/sessions'
      preLoaderRoute: typeof AuthEventlayoutOrgslugEventslugSessionsIndexImport
      parentRoute: typeof AuthEventlayoutImport
    }
  }
}

// Create and export the route tree

interface AuthEventlayoutRouteChildren {
  AuthEventlayoutOrgslugEventslugAttendeesRoute: typeof AuthEventlayoutOrgslugEventslugAttendeesRoute
  AuthEventlayoutOrgslugEventslugSettingsRoute: typeof AuthEventlayoutOrgslugEventslugSettingsRoute
  AuthEventlayoutOrgslugEventslugSpeakersRoute: typeof AuthEventlayoutOrgslugEventslugSpeakersRoute
  AuthEventlayoutOrgslugEventslugSponsorsRoute: typeof AuthEventlayoutOrgslugEventslugSponsorsRoute
  AuthEventlayoutOrgslugEventslugIndexRoute: typeof AuthEventlayoutOrgslugEventslugIndexRoute
  AuthEventlayoutOrgslugEventslugSessionsSessionslugRoute: typeof AuthEventlayoutOrgslugEventslugSessionsSessionslugRoute
  AuthEventlayoutOrgslugEventslugSessionsIndexRoute: typeof AuthEventlayoutOrgslugEventslugSessionsIndexRoute
}

const AuthEventlayoutRouteChildren: AuthEventlayoutRouteChildren = {
  AuthEventlayoutOrgslugEventslugAttendeesRoute:
    AuthEventlayoutOrgslugEventslugAttendeesRoute,
  AuthEventlayoutOrgslugEventslugSettingsRoute:
    AuthEventlayoutOrgslugEventslugSettingsRoute,
  AuthEventlayoutOrgslugEventslugSpeakersRoute:
    AuthEventlayoutOrgslugEventslugSpeakersRoute,
  AuthEventlayoutOrgslugEventslugSponsorsRoute:
    AuthEventlayoutOrgslugEventslugSponsorsRoute,
  AuthEventlayoutOrgslugEventslugIndexRoute:
    AuthEventlayoutOrgslugEventslugIndexRoute,
  AuthEventlayoutOrgslugEventslugSessionsSessionslugRoute:
    AuthEventlayoutOrgslugEventslugSessionsSessionslugRoute,
  AuthEventlayoutOrgslugEventslugSessionsIndexRoute:
    AuthEventlayoutOrgslugEventslugSessionsIndexRoute,
}

const AuthEventlayoutRouteWithChildren = AuthEventlayoutRoute._addFileChildren(
  AuthEventlayoutRouteChildren,
)

interface AuthOrglayoutRouteChildren {
  AuthOrglayoutOrgsIndexRoute: typeof AuthOrglayoutOrgsIndexRoute
  AuthOrglayoutOrgsOrgslugEventsRoute: typeof AuthOrglayoutOrgsOrgslugEventsRoute
}

const AuthOrglayoutRouteChildren: AuthOrglayoutRouteChildren = {
  AuthOrglayoutOrgsIndexRoute: AuthOrglayoutOrgsIndexRoute,
  AuthOrglayoutOrgsOrgslugEventsRoute: AuthOrglayoutOrgsOrgslugEventsRoute,
}

const AuthOrglayoutRouteWithChildren = AuthOrglayoutRoute._addFileChildren(
  AuthOrglayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthBaseRoute: typeof AuthBaseRoute
  AuthEventlayoutRoute: typeof AuthEventlayoutRouteWithChildren
  AuthOrglayoutRoute: typeof AuthOrglayoutRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBaseRoute: AuthBaseRoute,
  AuthEventlayoutRoute: AuthEventlayoutRouteWithChildren,
  AuthOrglayoutRoute: AuthOrglayoutRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthOrglayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthAdminRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/orgs': typeof AuthOrglayoutOrgsIndexRoute
  '/$org_slug/$event_slug/attendees': typeof AuthEventlayoutOrgslugEventslugAttendeesRoute
  '/$org_slug/$event_slug/settings': typeof AuthEventlayoutOrgslugEventslugSettingsRoute
  '/$org_slug/$event_slug/speakers': typeof AuthEventlayoutOrgslugEventslugSpeakersRoute
  '/$org_slug/$event_slug/sponsors': typeof AuthEventlayoutOrgslugEventslugSponsorsRoute
  '/orgs/$org_slug/events': typeof AuthOrglayoutOrgsOrgslugEventsRoute
  '/$org_slug/$event_slug': typeof AuthEventlayoutOrgslugEventslugIndexRoute
  '/$org_slug/$event_slug/sessions/$session_slug': typeof AuthEventlayoutOrgslugEventslugSessionsSessionslugRoute
  '/$org_slug/$event_slug/sessions': typeof AuthEventlayoutOrgslugEventslugSessionsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '': typeof AuthOrglayoutRouteWithChildren
  '/admin': typeof AuthAdminRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/orgs': typeof AuthOrglayoutOrgsIndexRoute
  '/$org_slug/$event_slug/attendees': typeof AuthEventlayoutOrgslugEventslugAttendeesRoute
  '/$org_slug/$event_slug/settings': typeof AuthEventlayoutOrgslugEventslugSettingsRoute
  '/$org_slug/$event_slug/speakers': typeof AuthEventlayoutOrgslugEventslugSpeakersRoute
  '/$org_slug/$event_slug/sponsors': typeof AuthEventlayoutOrgslugEventslugSponsorsRoute
  '/orgs/$org_slug/events': typeof AuthOrglayoutOrgsOrgslugEventsRoute
  '/$org_slug/$event_slug': typeof AuthEventlayoutOrgslugEventslugIndexRoute
  '/$org_slug/$event_slug/sessions/$session_slug': typeof AuthEventlayoutOrgslugEventslugSessionsSessionslugRoute
  '/$org_slug/$event_slug/sessions': typeof AuthEventlayoutOrgslugEventslugSessionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_auth/_base': typeof AuthBaseRoute
  '/_auth/_event_layout': typeof AuthEventlayoutRouteWithChildren
  '/_auth/_org_layout': typeof AuthOrglayoutRouteWithChildren
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/_org_layout/orgs/': typeof AuthOrglayoutOrgsIndexRoute
  '/_auth/_event_layout/$org_slug/$event_slug/attendees': typeof AuthEventlayoutOrgslugEventslugAttendeesRoute
  '/_auth/_event_layout/$org_slug/$event_slug/settings': typeof AuthEventlayoutOrgslugEventslugSettingsRoute
  '/_auth/_event_layout/$org_slug/$event_slug/speakers': typeof AuthEventlayoutOrgslugEventslugSpeakersRoute
  '/_auth/_event_layout/$org_slug/$event_slug/sponsors': typeof AuthEventlayoutOrgslugEventslugSponsorsRoute
  '/_auth/_org_layout/orgs/$org_slug/events': typeof AuthOrglayoutOrgsOrgslugEventsRoute
  '/_auth/_event_layout/$org_slug/$event_slug/': typeof AuthEventlayoutOrgslugEventslugIndexRoute
  '/_auth/_event_layout/$org_slug/$event_slug/sessions/$session_slug': typeof AuthEventlayoutOrgslugEventslugSessionsSessionslugRoute
  '/_auth/_event_layout/$org_slug/$event_slug/sessions/': typeof AuthEventlayoutOrgslugEventslugSessionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/orgs'
    | '/$org_slug/$event_slug/attendees'
    | '/$org_slug/$event_slug/settings'
    | '/$org_slug/$event_slug/speakers'
    | '/$org_slug/$event_slug/sponsors'
    | '/orgs/$org_slug/events'
    | '/$org_slug/$event_slug'
    | '/$org_slug/$event_slug/sessions/$session_slug'
    | '/$org_slug/$event_slug/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | ''
    | '/admin'
    | '/settings'
    | '/'
    | '/orgs'
    | '/$org_slug/$event_slug/attendees'
    | '/$org_slug/$event_slug/settings'
    | '/$org_slug/$event_slug/speakers'
    | '/$org_slug/$event_slug/sponsors'
    | '/orgs/$org_slug/events'
    | '/$org_slug/$event_slug'
    | '/$org_slug/$event_slug/sessions/$session_slug'
    | '/$org_slug/$event_slug/sessions'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_auth/_base'
    | '/_auth/_event_layout'
    | '/_auth/_org_layout'
    | '/_auth/admin'
    | '/_auth/settings'
    | '/_auth/'
    | '/_auth/_org_layout/orgs/'
    | '/_auth/_event_layout/$org_slug/$event_slug/attendees'
    | '/_auth/_event_layout/$org_slug/$event_slug/settings'
    | '/_auth/_event_layout/$org_slug/$event_slug/speakers'
    | '/_auth/_event_layout/$org_slug/$event_slug/sponsors'
    | '/_auth/_org_layout/orgs/$org_slug/events'
    | '/_auth/_event_layout/$org_slug/$event_slug/'
    | '/_auth/_event_layout/$org_slug/$event_slug/sessions/$session_slug'
    | '/_auth/_event_layout/$org_slug/$event_slug/sessions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/recover-password",
        "/reset-password",
        "/signup"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_base",
        "/_auth/_event_layout",
        "/_auth/_org_layout",
        "/_auth/admin",
        "/_auth/settings",
        "/_auth/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/recover-password": {
      "filePath": "recover-password.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_auth/_base": {
      "filePath": "_auth/_base.tsx",
      "parent": "/_auth"
    },
    "/_auth/_event_layout": {
      "filePath": "_auth/_event_layout.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_event_layout/$org_slug/$event_slug/attendees",
        "/_auth/_event_layout/$org_slug/$event_slug/settings",
        "/_auth/_event_layout/$org_slug/$event_slug/speakers",
        "/_auth/_event_layout/$org_slug/$event_slug/sponsors",
        "/_auth/_event_layout/$org_slug/$event_slug/",
        "/_auth/_event_layout/$org_slug/$event_slug/sessions/$session_slug",
        "/_auth/_event_layout/$org_slug/$event_slug/sessions/"
      ]
    },
    "/_auth/_org_layout": {
      "filePath": "_auth/_org_layout.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_org_layout/orgs/",
        "/_auth/_org_layout/orgs/$org_slug/events"
      ]
    },
    "/_auth/admin": {
      "filePath": "_auth/admin.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings": {
      "filePath": "_auth/settings.tsx",
      "parent": "/_auth"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/_org_layout/orgs/": {
      "filePath": "_auth/_org_layout/orgs.index.tsx",
      "parent": "/_auth/_org_layout"
    },
    "/_auth/_event_layout/$org_slug/$event_slug/attendees": {
      "filePath": "_auth/_event_layout/$org_slug.$event_slug.attendees.tsx",
      "parent": "/_auth/_event_layout"
    },
    "/_auth/_event_layout/$org_slug/$event_slug/settings": {
      "filePath": "_auth/_event_layout/$org_slug.$event_slug.settings.tsx",
      "parent": "/_auth/_event_layout"
    },
    "/_auth/_event_layout/$org_slug/$event_slug/speakers": {
      "filePath": "_auth/_event_layout/$org_slug.$event_slug.speakers.tsx",
      "parent": "/_auth/_event_layout"
    },
    "/_auth/_event_layout/$org_slug/$event_slug/sponsors": {
      "filePath": "_auth/_event_layout/$org_slug.$event_slug.sponsors.tsx",
      "parent": "/_auth/_event_layout"
    },
    "/_auth/_org_layout/orgs/$org_slug/events": {
      "filePath": "_auth/_org_layout/orgs.$org_slug.events.tsx",
      "parent": "/_auth/_org_layout"
    },
    "/_auth/_event_layout/$org_slug/$event_slug/": {
      "filePath": "_auth/_event_layout/$org_slug.$event_slug.index.tsx",
      "parent": "/_auth/_event_layout"
    },
    "/_auth/_event_layout/$org_slug/$event_slug/sessions/$session_slug": {
      "filePath": "_auth/_event_layout/$org_slug.$event_slug.sessions.$session_slug.tsx",
      "parent": "/_auth/_event_layout"
    },
    "/_auth/_event_layout/$org_slug/$event_slug/sessions/": {
      "filePath": "_auth/_event_layout/$org_slug.$event_slug.sessions.index.tsx",
      "parent": "/_auth/_event_layout"
    }
  }
}
ROUTE_MANIFEST_END */
